###
POST http://localhost:8081/residents/1 HTTP/1.1
Content-Type: application/json

{
  "familySerialNo": 3,
  "relationship": "아들"
}

###
PUT http://localhost:8081/residents/1/relationship/2 HTTP/1.1
Content-Type: application/json

{
  "relationship": "부"
}

###
DELETE http://localhost:8081/residents/7/relationship/5