###
POST http://localhost:8080/household/1/movement HTTP/1.1
Content-Type: application/json

{
  "reportDate": "1999-09-09",
  "movementAddress": "마산"
}

###
PUT http://localhost:8080/household/1/movement/20091031 HTTP/1.1
Content-Type: application/json

{
  "address": "창원시 마산합포구"
}
###
DELETE http://localhost:8080/household/1/movement/20091031